# Generated by Django 4.2.3 on 2023-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.CharField(choices=[('dicas', 'Dicas'), ('eventos', 'Eventos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tip_about',
            field=models.CharField(choices=[('desempenho', 'Desempenho'), ('ira', 'IRA'), ('bolsas', 'Bolsas'), ('cursos', 'Cursos')], max_length=20),
        ),
    ]
